version: 0.2

env:
  variables:
    BUILD_VERSION: 1.0.0
  parameter-store:
    ECR_REPOSITORY_SATELLITE_API: /CodeBuild/ECR_REPOSITORY_SATELLITE_API
    KUBECTL_ROLE_ARN_SATELLITE_API: /CodeBuild/KUBECTL_ROLE_ARN_SATELLITE_API
    KUBERNETES_CLUSTER_NAME_SATELLITE_API: /CodeBuild/KUBERNETES_CLUSTER_NAME_SATELLITE_API
    

phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - echo "... Authenticating to Elastic Container Registry ..."
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - echo "... Installing Required Cli Tools to Execute Automated Build and Deployments ..."
      - curl -Ss -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.9/2020-08-04/bin/linux/amd64/aws-iam-authenticator
      - curl -Ss -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.9/2020-08-04/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - mkdir -p $HOME/codebuild && export PATH=$PATH:$HOME/codebuild && export KUBECONFIG=$HOME/.kube/config
      - cp ./aws-iam-authenticator $HOME/codebuild/aws-iam-authenticator && cp ./kubectl $HOME/codebuild/kubectl
      - pip install --upgrade pip && pip install --upgrade awscli
  pre_build:
    commands:
      - echo "... Executing Unit Test ..."
      - dotnet test test/SatelliteApi.Tests
  build:
    commands:
      - echo "... Building Container ..."
      - docker build -t $ECR_REPOSITORY_SATELLITE_API:$BUILD_VERSION .
      - docker push $ECR_REPOSITORY_SATELLITE_API:$BUILD_VERSION
  post_build:
    commands:
      - echo "... Post-Build Phase ..."
      - aws eks update-kubeconfig --name $KUBERNETES_CLUSTER_NAME_SATELLITE_API --role-arn $KUBECTL_ROLE_ARN_SATELLITE_API
      - sed -i "s/VERSION/$BUILD_VERSION/g" kubernetes.yml
      - kubectl apply -f kubernetes.yml